[settings]
experimental = true

[tools]
npm = "latest"
pnpm = "latest"
node = "lts"
'npm:nx' = 'latest'
'npm:@anthropic-ai/claude-code' = "latest"

go = "latest"
"go:github.com/766b/go-outliner" = "latest"

aws = "latest"
doctl = "latest"
terraform = "1.14.1"

[env]
_.path = ["{{config_root}}/node_modules/.bin"]
AWS_PAGER = ""
VITE_MODE = "development"

[tasks.devcontainer_init]
hide = true
run = [
  "ln -s -t ~ /mnt/home/.aws",
  "ln -s -t ~/.config '/mnt/home/Library/Application Support/doctl'",
  "ln -s -t ~ /mnt/home/.npmrc",
  "pnpm install",
  "pnpm build || true",
]
