[settings]
experimental = true

[tools]
npm = "latest"
node = "lts"
go = "1.26.0"

[env]
_.path = ["{{config_root}}/node_modules/.bin"]
AWS_PAGER = ""
VITE_MODE = "development"

[tasks.devcontainer_init]
hide = true
run = [
  "ln -s -t ~ /mnt/home/.aws",
  "ln -s -t ~/.config '/mnt/home/Library/Application Support/doctl'",
  "ln -s -t ~ /mnt/home/.npmrc",
  "npm ci",
]
