name: Go Publish
run-name: ${{ github.workflow }}

on:
  workflow_dispatch: {}
  push:
    branches: [main]
    paths:
      - ".github/**"
      - "go/*/version"

env:
  TERM: xterm-256color
  FORCE_COLOR: 1

concurrency:
  group: ${{ github.workflow }}

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Publish
        run: |
          set -e
          initial_commit=$(git rev-parse HEAD)
          for filename in go/*/version; do
            git reset --hard "$initial_commit" &>/dev/null

            version_commit=$(git rev-list -1 HEAD -- "$filename")
            dir=$(dirname "$filename")
            version=$(head -n 1 "$filename")
            tag="${dir}/v${version}"

            echo "Publishing ${tag}..."
            git reset --hard "$version_commit" &>/dev/null
            (cd "$dir" && go mod tidy &>/dev/null)
            if ! git diff-index --quiet HEAD -- "$dir"; then
              echo "Uncommitted changes in \"$dir\" after 'go mod tidy'. Skipping publish."
              continue
            fi
            if ! git tag "$tag"; then
              continue
            fi
            git push origin tag "$tag"
          done