name: Go Publish
run-name: ${{ github.workflow }}

on:
  workflow_dispatch: {}
  push:
    branches: [main]
    paths:
      - ".github/**"
      - "go/*/version"

env:
  TERM: xterm-256color
  FORCE_COLOR: 1

concurrency:
  group: ${{ github.workflow }}

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Publish
        run: |
          set -e
          initial_commit=$(git rev-parse HEAD)
          for filename in go/*/version; do
            (
              set -e
              git reset --hard "$initial_commit" &>/dev/null
              dir=$(dirname "$filename")
              version=$(head -n 1 "$filename")
              tag="${dir}/v${version}"

              echo "::group::Publishing ${tag}"
              version_commit=$(git rev-list -1 HEAD -- "$filename")
              git reset --hard "$version_commit"
              cd "$dir"
              go mod tidy

              if ! git diff-index --quiet HEAD -- "$dir"; then
                echo "Uncommitted changes in \"$dir\". Skipping publish."
                exit
              fi

              go test -v -count=1

              if ! git tag "$tag"; then
                exit
              fi

              git push origin tag "$tag"
              module=$(cat go.mod | grep --color=never -Po '(?<=^module )\S+$')
              GOPROXY=proxy.golang.org go list -m "${module}@v${version}" || true
            )
            echo ::endgroup::
          done