name: Go Publish
run-name: ${{ github.workflow }}

on:
  workflow_dispatch: {}
  push:
    branches: [main]
    paths:
      - ".github/**"
      - "go/**"

env:
  TERM: xterm-256color
  FORCE_COLOR: 1

concurrency:
  group: ${{ github.workflow }}

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Publish
        run: |
          set -e
          error=0
          for filename in go/*/go.version; do
            (
              set -e
              dir=$(dirname "$filename")
              version=$(head -n 1 "$filename")
              tag="${dir}/v${version}"

              if [ $(git tag -l "$tag") ]; then
                exit
              fi

              echo "::group::Publishing ${tag}"
              cd "$dir"
              go mod tidy

              if ! git diff-index --quiet HEAD -- "$dir"; then
                echo "Uncommitted changes in \"$dir\". Skipping publish."
                exit
              fi

              go test -v -count=1
              git tag "$tag"
              git push origin tag "$tag"

              module=$(cat go.mod | grep --color=never -Po '(?<=^module )\S+$')
              GOPROXY=proxy.golang.org go list -m "${module}@v${version}" &>/dev/null || true
            )

            if [ $? -ne 0 ]; then
              error=1
            fi

            echo ::endgroup::
          done
          exit $error