name: NPM Publish
run-name: ${{ github.workflow }}

on:
  workflow_dispatch: {}
  push:
    branches: [main]
    tags: ['release-*']
    paths-ignore:
      - ".devcontainer/**"
      - "apps/**"
      - "templates/**"

env:
  TERM: xterm-256color
  FORCE_COLOR: 1
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

concurrency:
  group: ${{ github.workflow }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Mise
        uses: jdx/mise-action@v2

      - name: NPM Auth
        run: npm config set -L user //registry.npmjs.org/:_authToken '${NPM_TOKEN}'

      - name: Restore
        run: pnpm install --frozen-lockfile

      - name: Build
        run: nx build root

      - name: Test
        run: nx test root

      - name: Publish
        if: github.ref_type == 'tag'
        run: npx rev publish
