name: NPM
run-name: ${{ github.workflow }}

on:
  workflow_dispatch: {}
  push:
    branches: [main]
    paths:
      - "packages/**"

env:
  TERM: xterm-256color
  FORCE_COLOR: 1

concurrency:
  group: ${{ github.workflow }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/actions/setup
        with:
          mise: true
          docker: false
          npm-token: ${{ secrets.NPM_TOKEN }}
          restore: pnpm install --frozen-lockfile

      - name: Build
        run: nx build root

      - name: Test
        run: nx test root

      - name: Publish
        working-directory: packages
        run: |
          set -ex
          npx @seahax/publish-precheck
          npx @seahax/publish-from-package
