name: Seahax Infra
run-name: ${{ github.workflow }}

on:
  workflow_dispatch: {}
  push:
    branches: [main]
    paths:
      - apps/seahax/terraform/**

concurrency:
  group: ${{ github.workflow }}

jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/seahax/terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          mise: true
          docker: false

      - name: Terraform
        run: |
          set -ex
          terraform init
          terraform plan -out=tfplan \
            -var="ghcr_token=${{ secrets.GHCR_TOKEN }}" \
            -var="smtp_token=${{ secrets.SEAHAX_SMTP_TOKEN }}"
          terraform apply tfplan
        env:
          # Required for DigitalOcean terraform provider
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          # Required for DigitalOcean Spaces (S3) terraform backend
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1" # Not the actual region, but needed to avoid errors
