name: Seahax App
run-name: ${{ github.workflow }}

on:
  workflow_dispatch: {}
  push:
    branches: [main]
    paths:
      - apps/seahax/**
      - "!apps/seahax/terraform/**"

env:
  IMAGE_NAME: app
  DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
  DIGITALOCEAN_APP_ID: 63dd351b-872f-4b32-9022-5e5eff697dcf

concurrency:
  group: ${{ github.workflow }}

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    defaults:
      run:
        working-directory: apps/seahax
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          mise: true
          docker: true
          docker-registry: ghcr.io
          docker-username: ${{ github.actor }}
          docker-password: ${{ secrets.GITHUB_TOKEN }}
          restore: pnpm install --frozen-lockfile

      - name: Build
        run: nx docker.build -- -t "ghcr.io/${GITHUB_REPOSITORY_OWNER}/${IMAGE_NAME}:latest"
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: Test
        run: nx test

      - name: Push
        run: docker push "ghcr.io/${GITHUB_REPOSITORY_OWNER}/${IMAGE_NAME}:latest"

      - name: Deploy
        run: doctl apps create-deployment ${{ secrets.DIGITALOCEAN_APP_ID }}
