name: Seahax Infra
run-name: ${{ github.workflow }}

on:
  workflow_dispatch: {}
  push:
    branches: [main]
    paths:
      - apps/seahax/terraform/**

concurrency:
  group: ${{ github.workflow }}

jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/seahax/terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          mise: true
          docker: false

      - name: Plan
        run: terraform plan -out=tfplan -var="smtp_token=${{ secrets.SEAHAX_SMTP_TOKEN }}"

      - name: Apply
        run: terraform apply tfplan
